In [6]:
import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]


 4.1 Exercise on Functions: Task- 1:
 Create a Python program that converts between different units of measurement.
 • The program should:
 1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
 2. Ask the user to input the value to be converted.
 3. Perform the conversion and display the result.
 4. Handle potential errors, such as invalid input or unsupported conversion types.

** • Requirements:**

 1. Functions: Define at least one function to perform the conversion.
 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
 3. User Input: Prompt the user to select the conversion type and input the value.
 4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
 return value.
 • Conversion Options:
 1. Length:– Convert meters (m) to feet (ft).– Convert feet (ft) to meters (m).
 2. Weight:– Convert kilograms (kg) to pounds (lbs).– Convert pounds (lbs) to kilograms (kg).
 3. Volume:– Convert liters (L) to gallons (gal).– Convert gallons (gal) to liters (L).


In [5]:
def unit_converter():
    """
    A simple unit conversion tool.
    """
    print("Select a conversion category:")
    print("1. Length (meters to feet, feet to meters)")
    print("2. Weight (kilograms to pounds, pounds to kilograms)")
    print("3. Volume (liters to gallons, gallons to liters)")

    option = input("Enter your choice (1, 2, or 3): ")
    try:
        if option == "1":
            amount = float(input("Enter the quantity: "))
            measurement = input("Specify the unit (m/ft): ")
            if measurement == "m":
                print(f"{amount} meters is equivalent to {amount * 3.28084} feet.")
            elif measurement == "ft":
                print(f"{amount} feet is equivalent to {amount / 3.28084} meters.")
            else:
                print("Unsupported unit provided.")

        elif option == "2":
            amount = float(input("Enter the quantity: "))
            measurement = input("Specify the unit (kg/lbs): ")
            if measurement == "kg":
                print(f"{amount} kilograms is equivalent to {amount * 2.20462} pounds.")
            elif measurement == "lbs":
                print(f"{amount} pounds is equivalent to {amount / 2.20462} kilograms.")
            else:
                print("Unsupported unit provided.")

        elif option == "3":
            amount = float(input("Enter the quantity: "))
            measurement = input("Specify the unit (L/gal): ")
            if measurement == "L":
                print(f"{amount} liters is equivalent to {amount * 0.264172} gallons.")
            elif measurement == "gal":
                print(f"{amount} gallons is equivalent to {amount / 0.264172} liters.")
            else:
                print("Unsupported unit provided.")
        else:
            print("Invalid selection. Please choose 1, 2, or 3.")
    except ValueError:
        print("Error: Please enter a valid numerical value.")

# Execute the unit converter
unit_converter()


Select a conversion category:
1. Length (meters to feet, feet to meters)
2. Weight (kilograms to pounds, pounds to kilograms)
3. Volume (liters to gallons, gallons to liters)
Enter your choice (1, 2, or 3): 2
Enter the quantity: 75
Specify the unit (kg/lbs): kg
75.0 kilograms is equivalent to 165.3465 pounds.


Task- 2:
 Create a Python program that performs various mathematical operations on a list of numbers.
 • The Program should:
 1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
 of the numbers).
 2. Ask the user to input a list of numbers (separated by spaces).

 3. Perform the selected operation and display the result.
 4. Handle potential errors, such as invalid input or empty lists.
 **• Requirements:**
 1. Functions: Define at least one function for each operation (sum, average, maximum, mini
mum).
 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
 empty lists).
 3. User Input: Prompt the user to select the operation and input the list of numbers.
 4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
 return value.

In [ ]:
## Task 2: Mathematical Operations on a List

def perform_math_operations():
    """
    Performs sum, average, max, and min operations on a list of numbers.
    """
    try:
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
        if not numbers:
            print("List is empty. Provide valid numbers.")
            return

        print("Choose operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("Enter 1, 2, 3, or 4: ")
        if choice == "1":
            print("Sum:", sum(numbers))
        elif choice == "2":
            print("Average:", sum(numbers) / len(numbers))
        elif choice == "3":
            print("Maximum:", max(numbers))
        elif choice == "4":
            print("Minimum:", min(numbers))
        else:
            print("Invalid choice.")
    except ValueError:
        print("Invalid input. Enter numeric values only.")

# Running the function
perform_math_operations()

Enter numbers separated by spaces: 12 22 55
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 4
Minimum: 12.0


4.2 Exercise on List Manipulation:

In [ ]:
## Task 3: List Manipulation

def extract_every_other(lst):
    """Returns every other element from the list."""
    return lst[::2]

def get_sublist(lst, start, end):
    """Returns a sublist from start to end indices."""
    return lst[start:end+1]

def reverse_list(lst):
    """Returns the reversed list."""
    return lst[::-1]

def remove_first_last(lst):
    """Removes the first and last elements."""
    return lst[1:-1]

def get_first_n(lst, n):
    """Returns the first n elements."""
    return lst[:n]

def get_last_n(lst, n):
    """Returns the last n elements."""
    return lst[-n:]

def reverse_skip(lst):
    """Extracts every second element from the second-to-last element backward."""
    return lst[-2::-2]

# Sample Execution
test_list = [1, 2, 3, 4, 5, 6]
print("Every Other Element:", extract_every_other(test_list))
print("Sublist (2-4):", get_sublist(test_list, 2, 4))
print("Reversed List:", reverse_list(test_list))
print("Without First & Last:", remove_first_last(test_list))
print("First 3 Elements:", get_first_n(test_list, 3))
print("Last 2 Elements:", get_last_n(test_list, 2))
print("Reverse Skip Elements:", reverse_skip(test_list))

Every Other Element: [1, 3, 5]
Sublist (2-4): [3, 4, 5]
Reversed List: [6, 5, 4, 3, 2, 1]
Without First & Last: [2, 3, 4, 5]
First 3 Elements: [1, 2, 3]
Last 2 Elements: [5, 6]
Reverse Skip Elements: [5, 3, 1]




4.3 Exercise on Nested List:


In [ ]:
## Task 3: Nested List Operations

def flatten(lst):
    """Flattens a nested list into a single list."""
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(flatten(sublist))
        else:
            flat_list.append(sublist)
    return flat_list

def access_nested_element(lst, indices):
    """Accesses a nested list element by indices."""
    for i in indices:
        lst = lst[i]
    return lst

def sum_nested(lst):
    """Sums all elements in a nested list."""
    return sum(sum_nested(sublist) if isinstance(sublist, list) else sublist for sublist in lst)

def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    return [remove_element(sublist, elem) if isinstance(sublist, list) else sublist for sublist in lst if sublist != elem]

def find_max(lst):
    """Finds the maximum element in a nested list."""
    return max(find_max(sublist) if isinstance(sublist, list) else sublist for sublist in lst)

def count_occurrences(lst, elem):
    """Counts how many times an element appears in a nested list."""
    return sum(count_occurrences(sublist, elem) if isinstance(sublist, list) else (1 if sublist == elem else 0) for sublist in lst)

def deep_flatten(lst):
    """Flattens a deeply nested list into a single list."""
    return flatten(lst)

def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

# Sample Execution
nested_list = [[1, 2], [3, [4, 5]], 6]
print("Flatten List:", flatten(nested_list))
print("Element at [1,1]:", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
print("Sum of Elements:", sum_nested(nested_list))
print("Remove Element 2:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
print("Max Element:", find_max(nested_list))
print("Count Occurrences of 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("Deep Flatten:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print("Average Nested:", average_nested([[1, 2], [3, 4], [5, 6]]))

Flatten List: [1, 2, 3, 4, 5, 6]
Element at [1,1]: 6
Sum of Elements: 21
Remove Element 2: [[1], [3], [4, 5]]
Max Element: 6
Count Occurrences of 2: 3
Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Average Nested: 3.5


10.1 Basic Vector and Matrix Operation with Numpy.
 Problem- 1: Array Creation:
 Complete the following Tasks:
 1. Initialize an empty array with size 2X2.
 2. Initialize an all one array with size 4X2.
 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))

# 2. Initialize an all-one array with size 4X2.
ones_array = np.ones((4, 2))

# 3. Return a new array of given shape and type, filled with a fill value.
fill_array = np.full((3, 3), 7)  # Example fill value: 7

# 4. Return a new array of zeros with the same shape and type as a given array.
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)

# 5. Return a new array of ones with the same shape and type as a given array.
ones_like_array = np.ones_like(reference_array)

# 6. Convert an existing list to a NumPy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)

# Displaying results
(empty_array, ones_array, fill_array, zeros_like_array, ones_like_array, numpy_array)


(array([[3.21723459e-316, 0.00000000e+000],
        [2.31297541e-312, 2.54639495e-312]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]),
 array([[0, 0, 0],
        [0, 0, 0]]),
 array([[1, 1, 1],
        [1, 1, 1]]),
 array([1, 2, 3, 4]))

Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
# 1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()

# 5. Create a 10x10 array with random values and find the min and max
random_matrix_10x10 = np.random.random((10, 10))
min_value = random_matrix_10x10.min()
max_value = random_matrix_10x10.max()

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4) set to 1

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0  # Set inside values to 0

# 9. Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Set alternate positions to 1
checkerboard[::2, 1::2] = 1

# Display results
(array_range, matrix_3x3, identity_matrix, mean_value, min_value, max_value, zero_array, reversed_arr, border_array, checkerboard)


(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 0.49774271168359074,
 0.0007506100705234608,
 0.9853411256434845,
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0, 4, 0, 0, 2, 1]),
 array([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]]))

Problem- 3: Array Operations:

In [ ]:
# Defining the given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y


# Display results
(add_xy)

array([[ 6,  8],
       [10, 13]])

In [ ]:
# 2. Subtract the two arrays
sub_xy = x - y
(sub_xy)



array([[-4, -4],
       [-4, -3]])

In [ ]:
# 3. Multiply the array x with an integer (choosing 3 as the multiplier)
mult_x = x * 3

(mult_x)

array([[ 3,  6],
       [ 9, 15]])

In [ ]:
# 4. Find the square of each element of the array x
square_x = np.square(x)

(square_x)

array([[ 1,  4],
       [ 9, 25]])

In [ ]:
# 5. Find the dot product
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y
(dot_vw, dot_xv, dot_xy)


(219,
 array([29, 77]),
 array([[19, 22],
        [50, 58]]))

In [ ]:
# 6. Concatenate x and y along rows and v and w along columns
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))


# Display results
(concat_xy_row, concat_vw_col)


(array([[1, 2],
        [3, 5],
        [5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]))

In [ ]:
# 7. Concatenate x and v (expecting an error due to shape mismatch)
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Attempting to concatenate x and v
except ValueError as e:
    concat_xv_error = str(e)  # Capture the error message
(concat_xv_error)

'all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)'

Problem- 4: Matrix Operations:

In [ ]:
# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A⁻¹ = I
A_inv = np.linalg.inv(A)  # Compute the inverse of A
identity_A = np.dot(A, A_inv)  # A * A⁻¹

(identity_A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [ ]:

# 2. Prove AB = BA
AB = np.dot(A, B)  # Compute A * B
BA = np.dot(B, A)  # Compute B * A
commutative_check = np.allclose(AB, BA)  # Check if AB == BA
(commutative_check)

False

In [ ]:

# 3. Prove (AB)ᵀ = Bᵀ Aᵀ
AB_T = np.transpose(AB)  # Compute (AB)ᵀ
BT_AT = np.dot(np.transpose(B), np.transpose(A))  # Compute Bᵀ Aᵀ
transpose_check = np.allclose(AB_T, BT_AT)  # Check if (AB)ᵀ == Bᵀ Aᵀ
(transpose_check)

True

In [ ]:

# Solve the system of linear equations using Inverse Methods
# AX = B
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])

# Solve for X using np.linalg.inv
A_inv_matrix = np.linalg.inv(A_matrix)  # Compute inverse of A
X_solution = np.dot(A_inv_matrix, B_matrix)  # Compute X = A⁻¹ * B

# Display results
(X_solution)

array([ 2.,  1., -2.])

 1. Element-wise Addition:
 • Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
 and Print the time taken for this operation.
 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation

10.2 Experiment: How Fast is Numpy

In [ ]:
import time

# Generate two lists of size 1,000,000
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

# Measure time for element-wise addition using Python lists
start_time_list = time.time()
list_sum = [list1[i] + list2[i] for i in range(1_000_000)]
end_time_list = time.time()
list_time_taken = end_time_list - start_time_list

# Generate two NumPy arrays of size 1,000,000
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

# Measure time for element-wise addition using NumPy arrays
start_time_numpy = time.time()
array_sum = array1 + array2  # Element-wise addition in NumPy
end_time_numpy = time.time()
numpy_time_taken = end_time_numpy - start_time_numpy

# Display the time taken for both methods
(list_time_taken, numpy_time_taken)


(0.1492772102355957, 0.00834512710571289)

 Element-wise Multiplication
 • Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.
 Measure and Print the time taken for this operation.
 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.

In [ ]:
# Measure time for element-wise multiplication using Python lists
start_time_list_mult = time.time()
list_product = [list1[i] * list2[i] for i in range(1_000_000)]
end_time_list_mult = time.time()
list_mult_time_taken = end_time_list_mult - start_time_list_mult

# Measure time for element-wise multiplication using NumPy arrays
start_time_numpy_mult = time.time()
array_product = array1 * array2  # Element-wise multiplication in NumPy
end_time_numpy_mult = time.time()
numpy_mult_time_taken = end_time_numpy_mult - start_time_numpy_mult

# Display the time taken for both methods
(list_mult_time_taken, numpy_mult_time_taken)


(0.10301923751831055, 0.007843971252441406)

 Dot Product
 • Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
 Print the time taken for this operation.
 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.

In [ ]:
# Measure time for dot product using Python lists
start_time_list_dot = time.time()
list_dot_product = sum(list1[i] * list2[i] for i in range(1_000_000))
end_time_list_dot = time.time()
list_dot_time_taken = end_time_list_dot - start_time_list_dot

# Measure time for dot product using NumPy arrays
start_time_numpy_dot = time.time()
array_dot_product = np.dot(array1, array2)  # Dot product in NumPy
end_time_numpy_dot = time.time()
numpy_dot_time_taken = end_time_numpy_dot - start_time_numpy_dot

# Display the time taken for both methods
(list_dot_time_taken, numpy_dot_time_taken)


(0.11536264419555664, 0.003011465072631836)

Matrix Multiplication
 • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea
sure and print the time taken for this operation.
 • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
 Measure and print the time taken for this operation.

In [ ]:
# Generate two matrices of size 1000x1000 using NumPy arrays
matrix1_numpy = np.random.rand(1000, 1000)
matrix2_numpy = np.random.rand(1000, 1000)

# Measure time for matrix multiplication using NumPy arrays
start_time_numpy_matmul = time.time()
result_matrix_numpy = np.dot(matrix1_numpy, matrix2_numpy)  # Matrix multiplication in NumPy
end_time_numpy_matmul = time.time()
numpy_matmul_time_taken = end_time_numpy_matmul - start_time_numpy_matmul

# Display the time taken for NumPy matrix multiplication
numpy_matmul_time_taken


0.07204461097717285

In [2]:
import time

# Generate two matrices of size 1000x1000 using Python lists
matrix1_list = [[i * j for j in range(1000)] for i in range(1000)]
matrix2_list = [[j * i for j in range(1000)] for i in range(1000)]

# Measure time for matrix multiplication using Python lists
start_time_list_matmul = time.time()
result_matrix_list = [[sum(matrix1_list[i][k] * matrix2_list[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time_list_matmul = time.time()

list_matmul_time_taken = end_time_list_matmul - start_time_list_matmul
print("Time taken for matrix multiplication using Python lists:", list_matmul_time_taken, "seconds")


Time taken for matrix multiplication using Python lists: 213.2465043067932 seconds
